# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1351, 648)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 60))
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(3, 5, 1341, 621))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app_icon = QtWidgets.QLabel(self.layoutWidget)
        self.app_icon.setMinimumSize(QtCore.QSize(60, 60))
        self.app_icon.setMaximumSize(QtCore.QSize(60, 60))
        self.app_icon.setText("")
        self.app_icon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.app_icon.setObjectName("app_icon")
        self.horizontalLayout.addWidget(self.app_icon)
        self.app_name = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_name.sizePolicy().hasHeightForWidth())
        self.app_name.setSizePolicy(sizePolicy)
        self.app_name.setMinimumSize(QtCore.QSize(200, 60))
        self.app_name.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.app_name.setFont(font)
        self.app_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.app_name.setObjectName("app_name")
        self.horizontalLayout.addWidget(self.app_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_date = QtWidgets.QLabel(self.layoutWidget)
        self.label_date.setMinimumSize(QtCore.QSize(30, 30))
        self.label_date.setMaximumSize(QtCore.QSize(30, 30))
        self.label_date.setText("")
        self.label_date.setObjectName("label_date")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_date)
        self.pushButton_date = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_date.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_date.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_date.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_date.setCheckable(True)
        self.pushButton_date.setObjectName("pushButton_date")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_date)
        self.label_place = QtWidgets.QLabel(self.layoutWidget)
        self.label_place.setMinimumSize(QtCore.QSize(30, 30))
        self.label_place.setMaximumSize(QtCore.QSize(30, 30))
        self.label_place.setText("")
        self.label_place.setObjectName("label_place")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_place)
        self.pushButton_place = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_place.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_place.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_place.setCheckable(True)
        self.pushButton_place.setObjectName("pushButton_place")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_place)
        self.label_people = QtWidgets.QLabel(self.layoutWidget)
        self.label_people.setMinimumSize(QtCore.QSize(30, 30))
        self.label_people.setMaximumSize(QtCore.QSize(30, 30))
        self.label_people.setText("")
        self.label_people.setObjectName("label_people")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_people)
        self.pushButton_people = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_people.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_people.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_people.setCheckable(True)
        self.pushButton_people.setObjectName("pushButton_people")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_people)
        self.label_thing = QtWidgets.QLabel(self.layoutWidget)
        self.label_thing.setMinimumSize(QtCore.QSize(30, 30))
        self.label_thing.setMaximumSize(QtCore.QSize(30, 30))
        self.label_thing.setText("")
        self.label_thing.setObjectName("label_thing")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_thing)
        self.pushButton_thing = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_thing.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_thing.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_thing.setCheckable(True)
        self.pushButton_thing.setObjectName("pushButton_thing")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_thing)
        self.label_search = QtWidgets.QLabel(self.layoutWidget)
        self.label_search.setMinimumSize(QtCore.QSize(30, 30))
        self.label_search.setMaximumSize(QtCore.QSize(30, 30))
        self.label_search.setText("")
        self.label_search.setObjectName("label_search")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_search)
        self.pushButton_search = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_search.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_search.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_search.setCheckable(True)
        self.pushButton_search.setObjectName("pushButton_search")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_search)
        self.label_import = QtWidgets.QLabel(self.layoutWidget)
        self.label_import.setMinimumSize(QtCore.QSize(30, 30))
        self.label_import.setMaximumSize(QtCore.QSize(30, 30))
        self.label_import.setText("")
        self.label_import.setObjectName("label_import")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_import)
        self.pushButton_import = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_import.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_import.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_import.setCheckable(True)
        self.pushButton_import.setObjectName("pushButton_import")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pushButton_import)
        self.label_setting = QtWidgets.QLabel(self.layoutWidget)
        self.label_setting.setMinimumSize(QtCore.QSize(30, 30))
        self.label_setting.setMaximumSize(QtCore.QSize(30, 30))
        self.label_setting.setText("")
        self.label_setting.setObjectName("label_setting")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_setting)
        self.pushButton_setting = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_setting.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_setting.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_setting.setCheckable(True)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton_setting)
        self.label_about = QtWidgets.QLabel(self.layoutWidget)
        self.label_about.setMinimumSize(QtCore.QSize(30, 30))
        self.label_about.setMaximumSize(QtCore.QSize(30, 30))
        self.label_about.setText("")
        self.label_about.setObjectName("label_about")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_about)
        self.pushButton_about = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_about.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_about.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_about.setCheckable(True)
        self.pushButton_about.setObjectName("pushButton_about")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pushButton_about)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.workArea = QtWidgets.QStackedWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.workArea.sizePolicy().hasHeightForWidth())
        self.workArea.setSizePolicy(sizePolicy)
        self.workArea.setMinimumSize(QtCore.QSize(800, 600))
        self.workArea.setAcceptDrops(False)
        self.workArea.setAutoFillBackground(True)
        self.workArea.setObjectName("workArea")
        self.horizontalLayout_2.addWidget(self.workArea)
        self.horizontalLayout_2.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.workArea.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Personal Moments (demo)"))
        self.app_name.setText(_translate("MainWindow", "Personal Moments"))
        self.pushButton_date.setText(_translate("MainWindow", "Date"))
        self.pushButton_place.setText(_translate("MainWindow", "Place"))
        self.pushButton_people.setText(_translate("MainWindow", "People"))
        self.pushButton_thing.setText(_translate("MainWindow", "Thing"))
        self.pushButton_search.setText(_translate("MainWindow", "Search"))
        self.pushButton_import.setText(_translate("MainWindow", "Import"))
        self.pushButton_setting.setText(_translate("MainWindow", "Setting"))
        self.pushButton_about.setText(_translate("MainWindow", "About"))


