# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/searchImageArea.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(947, 581)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(7, 5, 921, 561))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_return = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_return.sizePolicy().hasHeightForWidth())
        self.pushButton_return.setSizePolicy(sizePolicy)
        self.pushButton_return.setText("")
        self.pushButton_return.setObjectName("pushButton_return")
        self.horizontalLayout.addWidget(self.pushButton_return)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_page_name = QtWidgets.QLabel(self.layoutWidget)
        self.label_page_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page_name.setObjectName("label_page_name")
        self.horizontalLayout.addWidget(self.label_page_name)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_fisrt = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_fisrt.sizePolicy().hasHeightForWidth())
        self.pushButton_fisrt.setSizePolicy(sizePolicy)
        self.pushButton_fisrt.setObjectName("pushButton_fisrt")
        self.horizontalLayout.addWidget(self.pushButton_fisrt)
        self.pushButton_previous = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_previous.sizePolicy().hasHeightForWidth())
        self.pushButton_previous.setSizePolicy(sizePolicy)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.horizontalLayout.addWidget(self.pushButton_previous)
        self.label_page_index = QtWidgets.QLabel(self.layoutWidget)
        self.label_page_index.setText("")
        self.label_page_index.setObjectName("label_page_index")
        self.horizontalLayout.addWidget(self.label_page_index)
        self.pushButton_next = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_next.sizePolicy().hasHeightForWidth())
        self.pushButton_next.setSizePolicy(sizePolicy)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout.addWidget(self.pushButton_next)
        self.pushButton_last = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_last.sizePolicy().hasHeightForWidth())
        self.pushButton_last.setSizePolicy(sizePolicy)
        self.pushButton_last.setObjectName("pushButton_last")
        self.horizontalLayout.addWidget(self.pushButton_last)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tableWidget_image = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidget_image.sizePolicy().hasHeightForWidth())
        self.tableWidget_image.setSizePolicy(sizePolicy)
        self.tableWidget_image.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget_image.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_image.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_image.setShowGrid(False)
        self.tableWidget_image.setRowCount(0)
        self.tableWidget_image.setColumnCount(0)
        self.tableWidget_image.setObjectName("tableWidget_image")
        self.tableWidget_image.horizontalHeader().setVisible(False)
        self.tableWidget_image.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_image.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget_image)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton_return, self.pushButton_fisrt)
        Form.setTabOrder(self.pushButton_fisrt, self.pushButton_previous)
        Form.setTabOrder(self.pushButton_previous, self.pushButton_next)
        Form.setTabOrder(self.pushButton_next, self.pushButton_last)
        Form.setTabOrder(self.pushButton_last, self.tableWidget_image)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_page_name.setText(_translate("Form", "Searching Results"))
        self.pushButton_fisrt.setText(_translate("Form", "First"))
        self.pushButton_previous.setText(_translate("Form", "Previous"))
        self.pushButton_next.setText(_translate("Form", "Next"))
        self.pushButton_last.setText(_translate("Form", "Last"))


